export const deals = [
  { company: "Stapleton Foundation Systems", source: "Platinum", city: "Macon", state: "GA", rev: 3.6, days: 93, tgt: 90, stage: "LOI Signed", health: "watch", status: "APA signed — targeting 3/30 close" },
  { company: "Stable Foundation Solutions", source: "Finder (JR)", city: "Richmond", state: "VA", rev: 5.6, days: 65, tgt: 90, stage: "LOI Signed", health: "on-track", status: "Under LOI — targeting 4/13 close" },
  { company: "Boccia Inc.", source: "PHG", city: "Long Island", state: "NY", rev: 8.0, days: 8, tgt: 20, stage: "NDA Signed", health: "on-track", status: "Follow-up call scheduled 3/18" },
  { company: "EverDry – Franchisor (EMMI)", source: "Exit", city: "Cleveland", state: "OH", rev: 10.0, days: 114, tgt: 20, stage: "NDA Signed", health: "at-risk", status: "Path forward to be assessed 3/23" },
  { company: "Stratum Structural Repair", source: "Exit", city: "St. Louis", state: "MO", rev: 7.5, days: 31, tgt: 30, stage: "Engaged", health: "watch", status: "Follow-up with Sam C (Exit) on 3/23" },
  { company: "United Dynamics", source: "PHG", city: "Louisville", state: "KY", rev: 6.0, days: 9, tgt: 30, stage: "Engaged", health: "on-track", status: "Follow-up with Matt L (PHG) on 3/23" },
  { company: "Falcone Crawl Space", source: "Exit", city: "Charlotte", state: "NC", rev: 5.0, days: 10, tgt: 30, stage: "Engaged", health: "on-track", status: "Follow-up with Dylan G (Exit) on 3/23" },
  { company: "Foundation Spec of MI", source: "Exit", city: "Grand Rapids", state: "MI", rev: 5.4, days: null, tgt: null, stage: "Owner Conv.", health: "on-track", status: "Andrew spoke with Bryan 3/16; following up 3/20" },
  { company: "Dalinghaus Construction", source: "Finder (DD)", city: "Los Angeles", state: "CA", rev: 30.0, days: null, tgt: null, stage: "Owner Conv.", health: "on-track", status: "Kevin and Brian connected 3/17" },
  { company: "603 Basement Solutions", source: "PHG", city: "East Kingston", state: "NH", rev: 3.2, days: null, tgt: null, stage: "Owner Conv.", health: "on-track", status: "$3.2M LTM Revenue vs. $2.4M last summer" },
  { company: "Cantey Foundation Specialists", source: "Finder (HB)", city: "Camden", state: "SC", rev: 35.0, days: null, tgt: null, stage: "Owner Conv.", health: "on-track", status: "HB reaching out to assess interest" },
  { company: "Re-Nu Crawlspace", source: "Finder (HB)", city: "Henderson", state: "KY", rev: 5.0, days: null, tgt: null, stage: "Owner Conv.", health: "on-track", status: "HB reaching out to assess interest" },
  { company: "Absolutely Dry", source: "Finder (JR)", city: "Davenport", state: "IA", rev: 5.0, days: null, tgt: null, stage: "Owner Conv.", health: "on-track", status: "Joe Ross reaching out week of 3/16" },
  { company: "Tomlinson Cannon", source: "Finder (JR)", city: "Cedar Rapids", state: "IA", rev: 5.0, days: null, tgt: null, stage: "Owner Conv.", health: "on-track", status: "Joe Ross reaching out week of 3/16" },
]

export const nurture = [
  { company: "HomeSpec", stage: "NDA Signed", state: "MI", region: "Midwest", rev: 14.0, ebitda: null, margin: null, source: "Proprietary", days: 490, note: "Todd in touch with Owner (Craig Ceccarelli)" },
  { company: "NorCal Foundation Support", stage: "NDA Signed", state: "CA", region: "Other", rev: 8.5, ebitda: null, margin: null, source: "Proprietary", days: 59, note: "Banker preparing marketing materials" },
  { company: "AMC911", stage: "NDA Signed", state: "VA", region: "Southeast", rev: 10.0, ebitda: 2.0, margin: 20, source: "Broker", days: 312, note: "Check-in call scheduled for mid-May" },
  { company: "Ohio State Waterproofing", stage: "NDA Signed", state: "OH", region: "Midwest", rev: 30.0, ebitda: null, margin: null, source: "Broker", days: 114, note: "Pursuing EverDry franchises ahead of Ohio State" },
  { company: "BAY Crawl Space & Foundation Repair", stage: "NDA Signed", state: "VA", region: "Southeast", rev: 15.0, ebitda: null, margin: null, source: "Proprietary", days: 70, note: "NDA signed; Kevin staying in touch" },
  { company: "Hitman Solutions", stage: "NDA Signed", state: "IN", region: "Midwest", rev: 6.0, ebitda: 1.0, margin: 17, source: "Proprietary", days: 274, note: "Andrew staying in touch with Trent & Jon (owners)" },
  { company: "AM Shield", stage: "NDA Signed", state: "NY", region: "Northeast", rev: 4.8, ebitda: 0.8, margin: 17, source: "Broker", days: 393, note: "Spoke with Hugo on 6/17; leads are down" },
  { company: "Professional Foundation Repair", stage: "NDA Signed", state: "CA", region: "Other", rev: 9.0, ebitda: null, margin: null, source: "Broker", days: 488, note: "Met with Darin during WoC; staying in touch" },
  { company: "KCS Foundation & Waterproofing", stage: "Engaged", state: "KY", region: "Southeast", rev: 9.0, ebitda: null, margin: null, source: "Finder (JT)", days: 57, note: "Setting up in-person meeting for June 2026" },
  { company: "Ground Up Foundation Repair", stage: "Engaged", state: "TN", region: "Southeast", rev: 6.0, ebitda: null, margin: null, source: "Broker", days: null, note: "Todd & Andrew reaching out to Derek (owner)" },
  { company: "Jamison Basement Waterproofing", stage: "Engaged", state: "PA", region: "Northeast", rev: 7.0, ebitda: null, margin: null, source: "Proprietary", days: 408, note: "Owner wants to reengage in 2026 following partner buyout" },
  { company: "Foundation Professionals of FL", stage: "Engaged", state: "FL", region: "Southeast", rev: 5.0, ebitda: null, margin: null, source: "Broker", days: 71, note: "Intro call occurred 1/13; assessing opportunity" },
  { company: "B-Dry Systems of Louisville", stage: "Engaged", state: "KY", region: "Southeast", rev: 5.0, ebitda: null, margin: null, source: "Broker", days: 134, note: "Attempting to get in touch with Keith O'Gara" },
  { company: "Ewing and Ray Foundation Services", stage: "Engaged", state: "MS", region: "Southeast", rev: 7.5, ebitda: null, margin: null, source: "Proprietary", days: 245, note: "Jonathan M in touch with Kip Ray (owner)" },
  { company: "Rapid Foundation Repair", stage: "Engaged", state: "SD", region: "Mountain West", rev: 4.0, ebitda: null, margin: null, source: "Broker", days: 372, note: "M&A team to engage late summer" },
  { company: "EverDry – Cincinnati", stage: "Engaged", state: "OH", region: "Midwest", rev: null, ebitda: null, margin: null, source: "Broker", days: 10, note: "Evaluating buy-out of Franchise — initial data request sent" },
  { company: "EverDry – Atlanta", stage: "Engaged", state: "GA", region: "Southeast", rev: null, ebitda: null, margin: null, source: "Broker", days: 10, note: "Evaluating buy-out of Franchise — initial data request sent" },
  { company: "EverDry – Rochester", stage: "Engaged", state: "NY", region: "Northeast", rev: null, ebitda: null, margin: null, source: "Broker", days: 10, note: "Evaluating buy-out of Franchise — initial data request sent" },
  { company: "EverDry – Grand Rapids", stage: "Engaged", state: "MI", region: "Midwest", rev: null, ebitda: null, margin: null, source: "Broker", days: 10, note: "Evaluating buy-out of Franchise — initial data request sent" },
  { company: "EverDry – Detroit", stage: "Engaged", state: "MI", region: "Midwest", rev: null, ebitda: null, margin: null, source: "Broker", days: 10, note: "Evaluating buy-out of Franchise — initial data request sent" },
  { company: "Southern Home Structural", stage: "Engaged", state: "AL", region: "Southeast", rev: 4.0, ebitda: null, margin: null, source: "Proprietary", days: 455, note: "Owner no longer interested per 2/12/25 — monitoring" },
  { company: "B-Dry Systems", stage: "Engaged", state: "KY", region: "Southeast", rev: null, ebitda: null, margin: null, source: "Broker", days: 134, note: "Attempting to get in touch with Keith O'Gara" },
  { company: "Acculevel", stage: "Owner Conv.", state: "IN", region: "Midwest", rev: 32.0, ebitda: 3.9, margin: 12, source: "Proprietary", days: 670, note: "Drip campaign; call with Andy Berry Dec-24 — focused on growth strategy", scale: true },
  { company: "American Waterworks", stage: "Owner Conv.", state: "MN", region: "Midwest", rev: 45.0, ebitda: null, margin: null, source: "Broker", days: 485, note: "CA checked in 2/11 — not interested in acquisition at this time", scale: true },
  { company: "Alabama Professional Services", stage: "Owner Conv.", state: "AL", region: "Southeast", rev: 20.0, ebitda: null, margin: null, source: "Proprietary", days: 1061, note: "Long-dated outreach", scale: true },
  { company: "Du-West Services", stage: "Owner Conv.", state: "TX", region: "Southwest", rev: 13.5, ebitda: null, margin: null, source: "Proprietary", days: 1027, note: "TBD", scale: true },
  { company: "Pioneer Basements", stage: "Owner Conv.", state: "RI", region: "Northeast", rev: 11.0, ebitda: null, margin: null, source: "Proprietary", days: 343, note: "Todd reaching back out to assess interest", scale: true },
  { company: "Vesta Foundation Solutions", stage: "Owner Conv.", state: "OK", region: "Midwest", rev: 15.0, ebitda: null, margin: null, source: "Proprietary", days: 485, note: "Interested in partnering but ~60% owned by Supportworks", scale: true },
  { company: "CenTex Foundation Repair", stage: "Owner Conv.", state: "TX", region: "Southwest", rev: 10.0, ebitda: null, margin: null, source: "Broker", days: 169, note: "Intro call 10/2; mid-2026 sale process — staying in touch", scale: true },
  { company: "Helicon", stage: "Owner Conv.", state: "FL", region: "Southeast", rev: 10.0, ebitda: null, margin: null, source: "Finder (HB)", days: 346, note: "Reaching out via HB Marshall", scale: true },
  { company: "Attic and Crawlspace Solutions", stage: "Owner Conv.", state: "SC", region: "Southeast", rev: 8.0, ebitda: null, margin: null, source: "Vendor (HB)", days: 312, note: "Moving to monitoring — service mix concerns" },
  { company: "Dura Pier Foundation Repair", stage: "Owner Conv.", state: "TX", region: "Southwest", rev: 8.0, ebitda: null, margin: null, source: "Proprietary", days: 963, note: "TBD" },
  { company: "Smart Foundation Systems", stage: "Owner Conv.", state: "MO", region: "Midwest", rev: 7.0, ebitda: null, margin: null, source: "Proprietary", days: 485, note: "Owner open to exploring a transaction; slow play" },
  { company: "Foundation Restoration", stage: "Owner Conv.", state: "MI", region: "Midwest", rev: 7.8, ebitda: null, margin: null, source: "Broker", days: 373, note: "Passing for now — young brand with low margin" },
  { company: "Coastal Crawl Space & FR", stage: "Owner Conv.", state: "NC", region: "Southeast", rev: 6.0, ebitda: null, margin: null, source: "Broker", days: 485, note: "Reaching out via Matt Walder once Stable closes" },
  { company: "Dry Tech Waterproofing Solutions", stage: "Owner Conv.", state: "PA", region: "Northeast", rev: 6.7, ebitda: null, margin: null, source: "Proprietary", days: 409, note: "Pursue Jamison first as preferred Philadelphia entry; moving to monitoring" },
  { company: "Healthy Spaces", stage: "Owner Conv.", state: "IN", region: "Midwest", rev: 5.3, ebitda: null, margin: null, source: "Proprietary", days: 485, note: "Seller in discussions with another buyer (likely Centeroak)" },
  { company: "Terratec Inc", stage: "Owner Conv.", state: "SC", region: "Southeast", rev: 5.0, ebitda: null, margin: null, source: "Proprietary", days: 273, note: "Sent YTD 2025 financials; gathering outstanding IDRL data" },
  { company: "Wolfe Construction", stage: "Owner Conv.", state: "NC", region: "Southeast", rev: 5.0, ebitda: null, margin: null, source: "Proprietary", days: 189, note: "Prioritizing behind Falcone due to scale and reputation" },
  { company: "Blue Umbrella Waterproofing", stage: "Owner Conv.", state: "NJ", region: "Northeast", rev: 5.0, ebitda: 1.0, margin: 20, source: "Proprietary", days: 672, note: "TBD" },
  { company: "Dry Otter Waterproofing", stage: "Owner Conv.", state: "NC", region: "Southeast", rev: 4.5, ebitda: 1.1, margin: 24, source: "Proprietary", days: 319, note: "Seller decided to hold business for growth" },
  { company: "Montana Basement Solutions", stage: "Owner Conv.", state: "MT", region: "Mountain West", rev: 4.5, ebitda: null, margin: null, source: "Proprietary", days: 189, note: "Intro call 9/11; plan to stay in touch due to size & service mix" },
  { company: "Rhino", stage: "Owner Conv.", state: "UT", region: "Mountain West", rev: 4.4, ebitda: null, margin: null, source: "Proprietary", days: 336, note: "Staying in touch until ready to engage" },
  { company: "Best Buy Waterproofing", stage: "Owner Conv.", state: "MD", region: "Northeast", rev: 4.0, ebitda: 0.8, margin: 20, source: "Proprietary", days: 368, note: "NDA signed 3/4; evaluating given 58F overlap" },
  { company: "Copper Fox Foundation Solutions", stage: "Owner Conv.", state: "VA", region: "Southeast", rev: 4.0, ebitda: null, margin: null, source: "Finder", days: 154, note: "Passing due to scale; will stay in touch" },
  { company: "IWP Foundation Repair", stage: "Owner Conv.", state: "KS", region: "Midwest", rev: 4.0, ebitda: null, margin: null, source: "Proprietary", days: 169, note: "Intro call 9/23; IWP obtaining third-party valuation" },
  { company: "Rapid Foundation Repair", stage: "Owner Conv.", state: "SD", region: "Mountain West", rev: 4.0, ebitda: null, margin: null, source: "Broker", days: 372, note: "SB products customer; engage late summer" },
  { company: "American Dry Basement Systems", stage: "Owner Conv.", state: "CT", region: "Northeast", rev: 4.8, ebitda: null, margin: null, source: "Broker", days: 315, note: "Monthly touchpoints with Peter O'Shea" },
  { company: "PierMagic", stage: "Owner Conv.", state: "MO", region: "Midwest", rev: 4.7, ebitda: 0.3, margin: 7, source: "Broker", days: 485, note: "Complete pre-LOI materials" },
  { company: "BAM Basements and Masons of Des Moines", stage: "Owner Conv.", state: "IA", region: "Midwest", rev: 2.5, ebitda: null, margin: null, source: "Proprietary", days: 485, note: "Slow play due to size" },
  { company: "Scaldino Basement Solutions", stage: "Owner Conv.", state: "NJ", region: "Northeast", rev: 2.5, ebitda: 0.5, margin: 20, source: "Proprietary", days: 492, note: "Catch-up call with Nick Scaldino occurred 9/5" },
  { company: "StableDry", stage: "Owner Conv.", state: "TN", region: "Southeast", rev: null, ebitda: null, margin: null, source: "Proprietary", days: 443, note: "Drip campaign", scale: true },
  { company: "Landmark", stage: "Owner Conv.", state: "IL", region: "Midwest", rev: null, ebitda: null, margin: null, source: "Proprietary", days: 443, note: "Drip campaign", scale: true },
  { company: "Solid Ground Solutions", stage: "Owner Conv.", state: "OH", region: "Midwest", rev: null, ebitda: null, margin: null, source: "Proprietary", days: 443, note: "Drip campaign", scale: true },
  { company: "Olshan Foundation Repair", stage: "Owner Conv.", state: "TX", region: "Southwest", rev: null, ebitda: null, margin: null, source: "Proprietary", days: 641, note: "Drip campaign", scale: true },
]

export const meta = {
  weekLabel: "Week of March 20, 2026",
  budgetData: [
    { m: "Jan", closed: 40.3, loi: 0, budget: 40.3 },
    { m: "Feb", closed: 40.3, loi: 0, budget: 40.3 },
    { m: "Mar", closed: 47.8, loi: 8.3, budget: 40.3 },
    { m: "Apr", closed: 47.8, loi: 8.3, budget: 47.1 },
    { m: "May", closed: 47.8, loi: 8.3, budget: 53.9 },
    { m: "Jun", closed: 47.8, loi: 8.3, budget: 60.7 },
    { m: "Jul", closed: 47.8, loi: 8.3, budget: 67.6 },
    { m: "Aug", closed: 47.8, loi: 8.3, budget: 81.2 },
    { m: "Sep", closed: 47.8, loi: 8.3, budget: 88.0 },
    { m: "Oct", closed: 47.8, loi: 8.3, budget: 101.7 },
    { m: "Nov", closed: 47.8, loi: 8.3, budget: 108.5 },
    { m: "Dec", closed: 47.8, loi: 8.3, budget: 115.3 },
  ],
  alerts: [
    { type: "pos", text: "Ahead of April budget by $9.9M — $57.0M projected vs. $47.1M target" },
    { type: "pos", text: "2 LOIs signed and progressing to close: Stapleton (Mar 30) and Stable (Apr 13)" },
    { type: "pos", text: "7 new owner conversations initiated this week, exceeding 5-per-week target" },
    { type: "warn", text: "YTD NDA conversion below target — 4 executed vs. 8 target; revenue gap of $8M" },
    { type: "warn", text: "EverDry Franchisor stalled at 114 days in Engaged stage vs. 30-day target" },
    { type: "neutral", text: "Cantey ($35M) and Dalinghaus ($30M) in early conversations — large-scale upside if converted" },
  ],
  kpis: {
    acquired: "$47.8M",
    acquiredSub: "2 deals closed",
    underLoi: "$9.2M",
    underLoiSub: "2 deals",
    projected: "$57.0M",
    projectedDelta: 9.9,
    projectedDeltaLabel: "+$9.9M vs. budget",
    fullYear: "$115.3M",
    fullYearSub: "$58.3M remaining",
    activePipeline: "$75M",
    activePipelineSub: "10 active deals",
  },
  ntm: [
    { co: "Stapleton Foundation Systems", state: "GA", rev: 3.6, bud: 0.0, sign: "03/14/26", close: "03/30/26", stage: "LOI Signed", status: "APA signed — targeting 3/30 close" },
    { co: "Stable Foundation Solutions", state: "VA", rev: 5.6, bud: 6.8, sign: "03/27/26", close: "04/13/26", stage: "LOI Signed", status: "Under LOI — targeting 4/13 close" },
    { co: "Open slot", state: "", rev: null, bud: 6.8, sign: "04/01/26", close: "05/04/26", stage: "Open", status: "" },
    { co: "Boccia Inc.", state: "NY", rev: 8.0, bud: 6.8, sign: "05/01/26", close: "06/01/26", stage: "NDA Signed", status: "NDA signed; follow-up call scheduled 3/18" },
    { co: "United Dynamics", state: "KY", rev: 6.0, bud: 6.8, sign: "06/01/26", close: "07/01/26", stage: "Engaged", status: "Follow-up with Matt L (PHG) on 3/23" },
    { co: "Stratum Structural Repair", state: "MO", rev: 7.5, bud: 13.6, sign: "07/01/26", close: "08/03/26", stage: "Engaged", status: "Follow-up with Sam C (Exit) on 3/23" },
    { co: "AMC911", state: "VA", rev: 10.0, bud: 6.8, sign: "08/03/26", close: "09/01/26", stage: "NDA Signed", status: "Check-in call scheduled for mid-May" },
    { co: "Hitman Solutions", state: "IN", rev: 6.0, bud: 13.6, sign: "09/01/26", close: "10/01/26", stage: "NDA Signed", status: "Staying in touch with Trent & Jon (owners)" },
    { co: "HomeSpec", state: "MI", rev: 14.0, bud: 6.8, sign: "10/01/26", close: "11/02/26", stage: "NDA Signed", status: "Todd in touch with Owner (Craig Ceccarelli)" },
    { co: "Foundation Spec of MI", state: "MI", rev: 5.4, bud: 6.8, sign: "11/02/26", close: "12/01/26", stage: "Owner Conv.", status: "Following up 3/20" },
    { co: "EverDry – Franchisor", state: "OH", rev: 10.0, bud: 6.8, sign: "12/01/26", close: "01/04/27", stage: "Engaged", status: "Assess path forward 3/23" },
    { co: "Coastal Crawl Space & FR", state: "NC", rev: 6.0, bud: 6.8, sign: "01/04/27", close: "02/01/27", stage: "Owner Conv.", status: "Via Matt Walder (Finder) once Stable closes" },
    { co: "Jamison Basement Waterproofing", state: "PA", rev: 7.0, bud: 6.8, sign: "02/01/27", close: "03/01/27", stage: "Engaged", status: "Owner wants to reengage in 2026" },
    { co: "Pioneer Basements", state: "RI", rev: 11.0, bud: 6.8, sign: "03/01/27", close: "04/05/27", stage: "Owner Conv.", status: "Todd reaching back out to assess interest" },
    { co: "Helicon", state: "FL", rev: 10.0, bud: 6.8, sign: "04/05/27", close: "05/03/27", stage: "Owner Conv.", status: "Reaching out via HB Marshall (Finder)" },
  ],
  scorecardVol: [
    { stage: "Owner conversations", conv: null, wA: 7, wT: 5, mA: 16, mT: 13, yA: 49, yT: 52, avgDays: 43, tgtDays: 30 },
    { stage: "NDAs", conv: "15%", wA: 0, wT: 1, mA: 1, mT: 2, yA: 4, yT: 8, avgDays: 41, tgtDays: 20 },
    { stage: "Data received", conv: "80%", wA: 0, wT: 1, mA: 0, mT: 2, yA: 2, yT: 6, avgDays: 21, tgtDays: 30 },
    { stage: "Pre-LOI approval", conv: "66%", wA: 0, wT: 0.4, mA: 0, mT: 1, yA: 2, yT: 4, avgDays: 8, tgtDays: 15 },
    { stage: "LOI", conv: "63%", wA: 0, wT: 0.3, mA: 0, mT: 1, yA: 1, yT: 3, avgDays: 90, tgtDays: 90 },
    { stage: "Closed", conv: "90%", wA: 0, wT: 0, mA: 1, mT: 0, yA: 2, yT: 1, avgDays: null, tgtDays: null },
  ],
  scorecardRev: [
    { stage: "NDAs", conv: "15%", wA: 0, wT: 7, mA: 8, mT: 14, yA: 47, yT: 55 },
    { stage: "Data received", conv: "80%", wA: 0, wT: 7, mA: 0, mT: 14, yA: 18, yT: 41 },
    { stage: "Pre-LOI approval", conv: "66%", wA: 0, wT: 0, mA: 0, mT: 7, yA: 8, yT: 27 },
    { stage: "LOI", conv: "63%", wA: 0, wT: 0, mA: 0, mT: 7, yA: 6, yT: 20 },
    { stage: "Closed", conv: "90%", wA: 0, wT: 0, mA: 8, mT: 0, yA: 48, yT: 40 },
  ],
}

export function getDefaultData() {
  return { deals, nurture, meta }
}
